---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(broom.mixed)
library(lme4)
```

# Imports

```{r}
d.exp3.raw <- dir('../../data/experiment3/', pattern = "experiment*", include.dirs = T,
                          recursive = F, full.names = T) %>%
  dir(pattern = '^games$', include.dirs = T, full.names = T, recursive = F) %>%
  dir(pattern = '*.csv', full.names = T, recursive = F) %>%
  map_df(~ suppressMessages(read_csv(., col_types = 'cicdddidd') %>% mutate(filename = .x))) %>%
  group_by(filename) %>%
  mutate(half = ifelse(tick < 1200, 'first', 'second'))  # use value from Exp. 1 since this was one minute longer

inactive_pids_firsthalf <- d.exp3.raw %>% group_by(pid) %>% summarize(t = max(tick)) %>% filter(t < 1200) %>% pull(pid)
```

```{r}
incomplete_games <- d.exp3.raw %>% group_by(filename) %>% summarize(t = max(tick)) %>% filter(t < 2879) %>% pull(filename)

d.exp3 <- d.exp3.raw %>%
  filter(!(filename %in% incomplete_games)) %>%
  group_by(filename, pid, half) %>%
  summarize(avg_score = mean(bg_val)) %>%
  separate(filename, into = c('date', 'n_players_planned', 'noise-difficulty', 'gameid'), sep = '_') %>%
  separate(`noise-difficulty`, into = c('noise', 'difficulty'), sep = '-') %>%
  filter(!(pid %in% inactive_pids_firsthalf)) %>%
  group_by(gameid) %>%
  mutate(n_players = length(unique(pid))) %>%
  mutate(difficulty = ifelse(difficulty == '2en01', 'high noise', 'low noise')) 

write_csv(d.exp3, here('data/experiment3/experiment3_preprocessed.csv'))
```

Coarse stats

```{r}
cat('before exclusions: ')
cat(d.exp3.raw %>% pull(pid) %>% unique() %>% length(), 'participants in', 
    d.exp3.raw %>% pull(filename) %>% unique() %>% length(), 'games\n')

cat('after exclusions: ')
cat(d.exp3 %>% pull(pid) %>% unique() %>% length(), 'participants in', 
    d.exp3 %>% pull(gameid) %>% unique() %>% length(), 'games')

d.exp3 %>% group_by(difficulty) %>% summarize(num_participants = length(unique(pid)), num_games = length(unique(gameid)))
d.exp3 %>% group_by(difficulty, n_players) %>% summarize(num_participants = length(unique(pid)), num_games = length(unique(gameid)))
```

# Performance analyses 

```{r}
d.exp3 <- read_csv(here('data/experiment3/experiment3_preprocessed.csv'))
```
## Figure 5

```{r}
scores.toplot <- d.exp3 %>%
  group_by(half, n_players, difficulty) %>%
  tidyboot::tidyboot_mean(avg_score, nboot = 1000)
  
scores.toplot %>%
  ungroup() %>%
  filter(half == 'second') %>%
  filter(n_players < 6)  %>%
  ggplot(aes(x = n_players, y = empirical_stat)) +
    geom_jitter(aes(y = avg_score), alpha = 0.1, data = d.exp3 %>% filter(n_players < 6) %>% filter(half == 'second'), height = 0, width = 0.1) +
    geom_point() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0)+
    geom_smooth(method = 'lm', se = F, formula = y ~ poly(x, 2), color = 'black') +
    facet_wrap(~ difficulty) +
    ylim(0.5, 0.9) +
    theme_few() +
    labs(x = "group size", y = "mean score") +
    theme(aspect.ratio = 1)

ggsave('performance-summary-raw.pdf', width = 5, height = 3, units = 'in')
```

## Full timeseries of performance (bins of 100)

```{r}
d.exp3.raw %>%
  left_join(d.exp3 %>% filter(half == 'second'), by = c('pid')) %>% 
  filter(n_players < 6) %>%
  group_by(tick = floor(tick / 100), difficulty, n_players) %>%
  summarize(avg_score = mean(bg_val)) %>%
  ggplot(aes(x = tick, y = avg_score)) +
    geom_point() +
    geom_smooth(method = 'lm', formula = y ~ poly(x, 2), se = F) +
    facet_grid(difficulty ~ n_players) +
    theme_few() +
    labs(x = "time (100 ticks)", y = "mean score") +
    theme(aspect.ratio = 1)
```

# Statistics for scores

Computed on avg participant-level scores

```{r}
library(lmerTest)
exp3.reg <- lmer(avg_score ~ poly(n_players, 2) * difficulty + (1 | gameid) + (1 | noise:difficulty),
   data = d.exp3 %>% filter(half == 'second'),
   contrasts = list(difficulty = contr.sum(2))) 

summary(exp3.reg)
confint(exp3.reg)
```

# States

Read in processed data

```{r message=F}
files <- list.files(path = here("data/experiment3/processed/"), 
                    pattern = "*.csv", 
                    full.names = T)
read_csv(files[1])
d_raw <- files %>%
  map(~ read_csv(.x) %>% 
        select(pid, tick, bg_val, state, facing, going_straight, copying_exploiting, facing_spinning, copying_reward)) %>%
  reduce(bind_rows)

d <- d_raw %>%
  left_join(d.exp3 %>% filter(half == 'second'), by = c('pid')) %>% 
  filter(!is.na(difficulty)) %>%
  mutate(state = ifelse(facing & going_straight, 'copying', state)) %>%
  mutate(copy = state == 'copying',
       exploit = state == 'exploiting',
       explore = state == 'exploring')
```

```{r}
state_counts <- d %>%
  group_by(bg_val) %>%
  mutate(len = length(state)) %>%
  group_by(bg_val, state) %>%
  summarize(total = length(tick), prop = total/mean(len))

state_proportions <- d %>%
  gather(state_bin, val, copy, exploit, explore) %>%
  group_by(bg_val, state_bin, difficulty) %>%
  summarise(m = mean(val))
```

Plot overall proportions

```{r}
state_counts %>%
  mutate(state = fct_relevel(state, 'copying', 'exploring', 'exploiting')) %>%
  ggplot(aes(x= bg_val, y = prop, fill=state)) +
    geom_area(stat='identity', alpha = 0.5) +
    scale_fill_brewer(palette = "Set1") +
    theme_few() +
    theme(aspect.ratio = 3) +
    labs(x="background value", y="proportion in state")

ggsave(here('exp3_states.pdf'))
```

Break out by noise condition

```{r}
state_proportions %>% 
  ungroup() %>%
  filter(bg_val > 0) %>%
  mutate(state_bin = fct_relevel(factor(state_bin), 'copy', 'explore', 'exploit')) %>%
  mutate(difficulty = fct_relevel(difficulty, 'low noise', 'high noise')) %>%
  ggplot(aes(x = bg_val, y = m, color = state_bin, alpha = difficulty)) +
    geom_line() +
    facet_wrap(~ state_bin) +
    theme_few() +
    theme(aspect.ratio = 1) +
    scale_color_brewer(palette = "Set1") +
    scale_alpha_discrete(range = c(0.5,1)) +
    labs(x="background value", y="proportion in state")

ggsave('../../../couzin_replication_tex/figures/states-broken-out.pdf')
```

```{r}
exp3.exploit <- d %>%
  glmer(exploit ~ scale(bg_val, scale=F) * difficulty + (1 | pid) + (1 | noise:difficulty),
        family = 'binomial',
        contrasts = list(difficulty=contr.sum(2)),
        data = .)

summary(exp3.exploit)
confint(exp3.exploit, parm = 'scale(bg_val, scale = F)', method = 'Wald')
confint(exp3.exploit, parm = 'scale(bg_val, scale = F):difficulty1', method = 'Wald')
```

```{r}
exp3.copy <- d %>%
  glmer(copy ~ scale(bg_val, scale=F) * difficulty + (1 | pid) + (1 | noise:difficulty),
        family = 'binomial',
        contrasts = list(difficulty=contr.sum(2)),
        data = .) 
summary(exp3.copy)
confint(exp3.copy, parm = 'scale(bg_val, scale = F):difficulty1', method = 'Wald')
```

```{r}
exp3.explore <- d %>%
  glmer(explore ~ scale(bg_val, scale=F) * difficulty + (1 | pid) + (1 | noise:difficulty),
        family = 'binomial',
        contrasts = list(difficulty=contr.sum(2)),
        data = .) 
summary(exp3.explore)
confint(exp3.explore, parm = 'scale(bg_val, scale = F):difficulty1', method = 'Wald')
```

```{r}
d %>%
  filter(state == 'copying') %>%
  filter(!is.na(copying_reward)) %>%
  group_by(noise_condition) %>%
  summarize(m = mean(copying_reward, na.rm=T))
```

```{r}
library(lmerTest)
d %>%
  filter(state == 'copying') %>%
  filter(!is.na(copying_reward)) %>%
  lmer(copying_reward ~ noise_condition + (1 | pid),
       data = .) %>%
  summary()
```

## Examine auto-correlations

```{r}
d.exp3.raw %>%
  left_join(d.exp3 %>% filter(half == 'second'), by = c('pid')) %>% 
  filter(n_players < 6) %>%
  group_by(filename, pid, n_players, difficulty) %>%
  summarize(lag_1 = cor(bg_val, lag(bg_val, 1), use="complete.obs"),
         lag_5 = cor(bg_val, lag(bg_val, 5), use="complete.obs"),
         lag_10 = cor(bg_val, lag(bg_val, 10), use="complete.obs"),
         lag_20 = cor(bg_val, lag(bg_val, 20), use="complete.obs"),
         lag_30 = cor(bg_val, lag(bg_val, 30), use="complete.obs"),
         lag_50 = cor(bg_val, lag(bg_val, 50), use="complete.obs"),
         lag_75 = cor(bg_val, lag(bg_val, 75), use="complete.obs"),
         lag_100 = cor(bg_val, lag(bg_val, 100), use="complete.obs")) %>%
  gather(lag, value, starts_with('lag')) %>%
  separate(lag, into = c('garbage', 'lag')) %>%
  group_by(n_players, difficulty, lag) %>%
  tidyboot::tidyboot_mean(value, nboot = 100) %>%
  ggplot(aes(x = as.numeric(lag), y = empirical_stat, color = n_players, group = n_players)) +
    geom_line() +
    facet_wrap(~ difficulty) +
    ggthemes::theme_few() +
    labs(x = "distance in ticks", y = "mean correlation of scores") +
    theme(aspect.ratio = 1, legend.position = 'top')
  
ggsave('exp3_lags.pdf', width = 5, height = 3, units = 'in')
```
