---
title: "R Notebook"
output: html_notebook
---

# Import 

```{r}
library(tidyverse)
library(tidyboot)
library(ggthemes)
library(here)
source('../helpers.R')
```

# Behavioral analysis

## Combine player data with metadata on bot locations

```{r}
d_raw <- read_csv(here('data/experiment2/all_games.csv')) %>%
  rowwise() %>%
  mutate(metadatafilestringpt1 = paste0(
            c(here('experiments/metadata/v2/v2'), bg_cond, 'close_'), 
            collapse = '-'), 
         metadatafilestringpt2 = paste0(
            c(close_cond, 'asocial-smart-0', sim_num,'social-simulation.csv'),
            collapse = '-'),
         metadatafilestring = paste0(c(metadatafilestringpt1, metadatafilestringpt2),
                                     collapse = '')) %>%
  select(-metadatafilestringpt1, -metadatafilestringpt2) %>%
  filter(round_type %in% c("nonsocial", "social")) %>%
  mutate(goal_condition = case_when(in_close == 1 ~ 'close',
                                    in_far == 1 ~ 'far',
                                    TRUE ~ 'none'))

window_times = d_raw %>%
  group_by(pid, in_close, in_far) %>%
  mutate(count= row_number(), 
         first_in_close_group = in_close & count==1,
         first_in_far_group = in_far & count == 1,
         last_in_close_group = in_close & count==length(in_close),
         last_in_far_group = in_far & count == length(in_far)) %>%
  filter(first_in_far_group | first_in_close_group | last_in_close_group | last_in_far_group) %>%
  select(pid, tick, first_in_far_group, first_in_close_group, last_in_close_group, last_in_far_group)

early_window_times = c(65, 160)
late_window_times = c(305, 400)
```

```{r}
relevant_files = unique(d_raw$metadatafilestring)

bot_locations <- relevant_files %>% 
  map( ~ suppressMessages(read_csv(.x)) %>% mutate(metadatafilestring = .x)) %>% 
  reduce(rbind) %>%
  filter(pid != 0) %>%
  rowwise() %>%
  mutate(pid = paste0(c("bot", pid), collapse = "")) %>%
  ungroup() %>%
  select(pid, x_pos, y_pos, tick, metadatafilestring) %>%
  gather(coord, value, x_pos, y_pos) %>% 
  separate(coord, into=c('coord', 'garbage')) %>%
  unite(key, pid, coord) %>% 
  select(-garbage) %>% 
  pivot_wider(names_from = key, values_from = value) 

d <- left_join(d_raw, bot_locations, by= c('metadatafilestring', 'tick')) 
```

## Calculate measures of interest between player and bot

```{r}
clicks = d %>% 
  select(-metadatafilestring, -in_close, -in_far) %>%
  group_by(pid) %>%
  mutate(click = lag(goal_x) != goal_x | lag(goal_y) != goal_y) %>%
  gather(bot, value, bot1_x:bot4_y) %>%
  separate(bot, into = c('botid', 'coord')) %>%
  spread(coord, value) %>%
  mutate(botWallVsSpot = case_when(botid %in% c('bot1', 'bot2') ~ bg_cond,
                                  TRUE ~ ifelse(bg_cond == 'wall', 'spot', 'wall'))) %>%
  mutate(dist_bw_goal_and_bot = dist(goal_x, goal_y, x, y),
         dist_bw_location_and_bot = dist(x_pos, y_pos, x, y),
         angle_bw_location_and_bot = angle(x_pos, y_pos, x, y),
         tmp = abs(angle - angle_bw_location_and_bot),
         gap_bw_current_angle_and_bot = ifelse(tmp > 180, 360 - tmp, tmp),
         botExploiting = lag(x) == x & lag(y) == y,
         insideEarlyWindow = between(tick, early_window_times[1], early_window_times[2]),
         insideLateWindow = between(tick, late_window_times[1], late_window_times[2]),
         window = ifelse(insideEarlyWindow, "early", ifelse(insideLateWindow, "late", "none"))) %>%
  group_by(pid, window) %>%
  mutate(goal_condition = first(goal_condition)) %>%
  filter(click) %>%
  group_by(pid, tick, botExploiting, goal_condition, round_type) %>%
  summarize(minDistance = min(dist_bw_goal_and_bot)) %>%
  ungroup()

```

## Visualize

Version with bootstrapped error bars

```{r}
library(ggthemes)
dodge <- position_dodge(width=1)

# clicks.lmer <- clicks %>%
#   filter(goal_condition != 'none') %>%
#   spread(botExploiting, minDistance) %>%
#   mutate(diff = `FALSE` - `TRUE`) %>%
#   filter(!is.na(diff)) %>%
#   select(-`TRUE`, -`FALSE`)
  
clicks.toplot <- clicks %>%
  mutate(botExploiting = ifelse(botExploiting, 'exploiting', 'not exploiting')) %>%
  mutate(goal_condition = ifelse(goal_condition == 'close', 'local condition', ifelse(goal_condition == 'far', 'distant condition', 'none'))) %>% 
  # group_by(pid, goal_condition, botExploiting, round_type) %>%
  # summarize(empirical_stat = mean(minDistance)) %>%
  # only look at windows during goal manipulation
  #filter(goal_condition != 'none') %>% 
  # bootstrap over participants, not individual click events
  mutate(empirical_stat = minDistance) 

clicks.toplot.means <- clicks.toplot %>%
  filter(!(goal_condition == 'none' & botExploiting == 'exploiting')) %>%
  group_by(goal_condition, botExploiting, round_type) %>%
  tidyboot_mean(empirical_stat)
  #tidyboot(empirical_stat, median, list('ci_lower' = ci_lower, 'mean' = mean, 'ci_upper' = ci_upper))

clicks.toplot.none <- clicks.toplot.means %>%
  filter(goal_condition == 'none')  %>%   filter(round_type == 'social') 
  
clicks.toplot.goals <- clicks.toplot.means %>%
  filter(goal_condition != 'none') %>%  filter(round_type == 'social') 

clicks.toplot %>%
  filter(goal_condition != 'none') %>%
  filter(round_type == 'social') %>%
  ungroup() %>%
  ggplot(aes(x = goal_condition, y = empirical_stat, color = botExploiting)) +
    geom_dotplot(alpha = 0.1, position = dodge, binaxis = 'y',
                 stackdir = 'center', method = 'histodot', binwidth = 7) +
    geom_boxplot(alpha = 0.5, position = dodge, outlier.shape = '', notch = T) +
    geom_hline(aes(yintercept = empirical_stat), data = clicks.toplot.none) +
    # geom_point(stat = 'identity', position = dodge, data = clicks.toplot.goals) +
    # geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper),
    #               position = dodge, width = 0, data = clicks.toplot.goals) +
    labs(x = "", y = "distance between bot and click", color = '') +
    theme_few() +
    ylim(0, 400) +
    #facet_wrap(~ round_type) +
    scale_color_colorblind() +
    theme(aspect.ratio = 1, legend.position = 'top') 

ggsave('./proximity.pdf', height = 3, width = 5, units = 'in')
```

## Stats

```{r}
library(lme4)
library(lmerTest)

# analysis of social condition
clicks %>%
  mutate(botExploiting = ifelse(botExploiting, 'exploiting', 'not exploiting')) %>%
  filter(goal_condition != 'none') %>%
  filter(round_type == 'social') %>%
  lmer(minDistance ~ goal_condition * botExploiting + (1 + goal_condition * botExploiting | pid),
       data = .) %>%
  summary()
```

```{r}
# analysis of nonsocial condition
clicks %>%
  filter(round_type != 'social') %>%
  filter(goal_condition != 'none') %>%
  lmer(minDistance ~ goal_condition * botExploiting + (1 + goal_condition * botExploiting | pid),
       data = .,
       control=lmerControl(optimizer = 'bobyqa')) %>%
  summary()
```

```{r}
# interaction of non-social condition
clicks %>%
  mutate(botExploiting = ifelse(botExploiting, 'exploiting', 'not exploiting')) %>%
  filter(goal_condition != 'none') %>%
  lmer(minDistance ~ round_type * botExploiting * goal_condition + (1 + round_type + botExploiting * goal_condition | pid),
            data = .,
       control = lmerControl(optimizer='bobyqa')) %>%
  summary()
```

```{r}
clicks %>%
  mutate(botExploiting = ifelse(botExploiting, 'exploiting', 'not exploiting')) %>%
  filter(goal_condition != 'none') %>%
  brms::brm(minDistance ~ round_type * botExploiting * goal_condition + (1 + round_type * botExploiting * goal_condition | pid),
            data = .) 
```

```{r}
dodge <- position_dodge(width=0.9)

clicks.toplot <- clicks %>% 
   mutate(botExploiting = ifelse(botExploiting, 'exploiting', 'not exploiting')) %>%
   filter(goal_condition != 'none') %>% 
   group_by(pid, tick, goal_condition, botExploiting) %>%
   summarize(gap_bw_current_angle_and_bot = min(gap_bw_current_angle_and_bot)) %>%
   group_by(botExploiting, goal_condition) %>%
   tidyboot_mean(gap_bw_current_angle_and_bot) 

ggplot(clicks.toplot, aes(x = botExploiting, y = empirical_stat, fill = goal_condition)) +
    geom_bar(stat = 'identity', position = dodge) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper),, width = 0, position = dodge) +
    theme_bw() +
    xlab("") +
    ylab("distance between bot and click") 
```