---
title: "R Notebook"
output: html_notebook
---

```{r echo=FALSE}
library(tidyverse)
library(lme4)
library(ggthemes)

d <- dir(path = "../../simulations/output/predictions-emergent/",
	    pattern = "simulation",
	    full.names = T) %>%
	  map(read_csv) %>%
	  reduce(rbind) 
```

```{r}
toplot <- d %>% 
  mutate(half = ifelse(tick > max(tick)/2, 'first', 'second')) %>%
  separate(exp, into = c('goal-type', 'n_players', 'strategy', 'game')) %>%
  group_by(n_players, half, game, strategy) %>%
  summarize(m = mean(bg_val)) %>%
  group_by(n_players, strategy, half) %>%
  tidyboot::tidyboot_mean(m) 

toplot %>%
  ggplot(aes(x = as.numeric(n_players), y = empirical_stat, color=half)) +
    geom_point() +
    #geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_few() +
    facet_wrap(~ strategy) +
    geom_smooth(method = 'lm', formula = y ~ poly(x, 2), se = F) +
    ylab("mean score") +
    xlab("number of players") +
    scale_x_continuous(breaks = c(1, 2, 3, 4, 5, 6)) +
    theme(aspect.ratio = 2/3) +
    ggthemes::scale_color_colorblind()

ggsave('./performance-summary-exp1.pdf', width = 5, height = 3, units = 'in', useDingbats = F)
```

```{r}
library(lmerTest)
d %>% 
  gather(half, score, first_half_score, second_half_score) %>%
  mutate(n_players = fn_players - 3.5) %>%
  mutate(score = 100*score) %>%
  lmer(score ~ n_players * half + (1 | game) + (1 | noise), 
       data = .,
       contrasts = list(half=contr.sum(2))) %>%
  summary()
```

## Experimental analysis of click data

```{r}
# Original angle measured clock-wise from top
# So we map to standard polar coordinate system
d_raw <- read_csv('../data/experiment1/raw_games/all_raw_games.csv') %>%
  mutate(angle = (360 - (angle - 90)) %% 360) 

player_locations <- d_raw %>%
  group_by(gameid) %>%
  mutate(pid = as.numeric(factor(pid))) %>%
  unite(pos, x_pos,y_pos, bg_val, velocity) %>%
  select(pid, tick, gameid, pos) %>%
  group_by(gameid, tick) %>%
  spread(pid, pos) %>%
  ungroup() 
  
tmp <- left_join(d_raw, player_locations, by = c('gameid', 'tick')) %>%
  left_join(d  %>% select(pid, fn_players) %>% ungroup(), by = c('pid')) %>%
  filter(fn_players > 1)

clicks <- tmp %>%
  group_by(pid) %>%
  mutate(click = lag(goal_x) != goal_x | lag(goal_y) != goal_y) %>%
  gather(playerid, value, `1`:`6`) %>%
  filter(!is.na(value)) %>%
  filter(click) %>%
  filter(tick > 1200) %>% 
  separate(value, into = c('player_x', 'player_y',
                           'player_bg_val','player_velocity'), sep = '_') %>%
  mutate(player_x = as.numeric(player_x),
         player_y =as.numeric(player_y),
         dist_bw_goal_and_player = dist(goal_x, goal_y, player_x,player_y),
         angle_bw_location_and_bot = angle(x_pos, y_pos, player_x, player_y),
         tmp = abs(angle - angle_bw_location_and_bot),
         gap_bw_current_angle_and_bot = ifelse(tmp > 180, 360 - tmp, tmp)
         #abs(angle- angle_bw_location_and_bot),
)

clicks %>% 
  arrange(gameid, pid, tick) %>%
  filter(!(gameid %in% inactive)) %>%
  ungroup() %>%
  filter(!(abs(x_pos - player_x) < 1 & 
            abs(y_pos - player_y) < 1)) %>%# Remove comparisons to oneself
  group_by(pid, tick, fn_players, bg_val, player_velocity) %>%
  summarize(minDistance = min(dist_bw_goal_and_player),
            minAngle = min(gap_bw_current_angle_and_bot)) %>%
  group_by(fn_players, pid,tick,bg_val) %>%
 filter(length(minDistance) > 1) %>%
  # spread(player_velocity,  minDistance) %>%
  # mutate(diff = `0` - `1`) %>%
  # group_by(pid,  bg_val) %>%
  # summarize(diff =  mean(diff)) %>%
  group_by(bg_val, fn_players, player_velocity) %>%
  summarize(dist =  mean(minDistance),
            angle = mean(minAngle))
``` 